apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-fastapi-app
  labels:
    app: my-fastapi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-fastapi-app
  template:
    metadata:
      labels:
        app: my-fastapi-app
    spec:
      containers:
      - name: my-fastapi-app-container
        image: murali90102/my-fastapi-app:latest
        env:
        - name: "APP_PORT"
          value: "80"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-fastapi-app
  labels:
    app: my-fastapi-app
spec:
  selector:
    app: my-fastapi-app
  type: NodePort
  ports:
  - nodePort: 31001
    port: 80
    targetPort: 80
